### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by colinross**
Really basic Dockerfile that should pretty well match the vagrant environment for all intents and purposes.  Obviously not audited or hardened, etc.

The link in the documentation is to my own personal (albeit public) docker hub image that is an automated build from my fork-- feel free to update that with an official account-- or not.

Sorry for the rushed PR, leaving town for the weekend, feel free to let it sit til Monday.

### CODE REVIEW

**Comment by pbnj** [comment]
Hi @colinross , 

Thank you for putting in the effort to build this docker container/image.

We considered using docker for this bootcamp and I experimented with Docker for this bootcamp a few weeks ago, but we decided to go with a Virtual Machine and Vagrant instead for multiple reasons:
1. In order for Docker to work on Mac OS X and Windows, users still needed to install Virtual Box. Therefore maintaining a docker container inside a linux VM on a Windows or OS X host added unnecessary complexity (especially networking - mapping ports between docker containers and the linux guest VM and then mapping the ports between the linux guest VM and the host)
2. Docker introduces a steeper learning curve compared to Vagrant. That is to say it is easier to manage virtual machines through VirtualBox and Vagrant than it is to manage docker containers.  
3. Docker has not been whitelisted yet. There are security issues and gaps that need to be addressed before we can endorse using containerization technology.

**Comment by slietz** [comment]
@pmbenjamin - colin and i discussed this.  If we can get the docker file running with the right level of security and others want to use it, its a good second option to Vagrant, not necessarily a replacement.  The other reason we decided not to use it is its lack of native Mac support.

**Comment by pbnj** [comment]
@slietz I don't mind testing & experimenting with this Dockerfile over the next few days, but if we merge it in, then we assume the responsibility for supporting it.

Just to expand on your last statement:

> The other reason we decided not to use it is its lack of native Mac support.

This is the biggest reason why I opted for a simple virtual machine approach. Docker had a networking bug in their OS X offering that is a pain to resolve.
The issue would occur every time I switch networks (e.g. using the OS X at home, then bringing it to work the next day). To resolve it, I would have to terminate the running Docker daemon and re-initialize it again using Kitematic (GUI-based Docker manager).

As a result, Docker announced plans to reduce their dependence on 3rd party virtualization software (e.g. Virtualbox) a few months ago, but now Docker will be managing a linux VM directly ([reference](http://www.infoworld.com/article/3047603/application-development/docker-goes-native-for-windows-and-mac.html)). This is still in _beta_ and I would hardly call it native Mac support.

**Comment by manningdigital** [comment]
Sorry all for the late reply, I was out of town and traveling.
@pmbenjamin: I fully understand your trepidation over support issues. You are right that native docker support is beta in the full sense of the term on both windows [hyper-v based] and mac [ https://github.com/mist64/xhyve ] as they transition over to utilizing the native hypervisiors mentioned.

Currently, where I feel like docker support (in the context of the devsecops bootcamp repo) fits is at a _user-contrib_ type level. It is available to those whom wish to utilize it as their own environment and skills/knowledge allow.

I think we can at least all agree that docker has enough critical mass of usage, even with it's 'beta' support that the project can support it this much (have a Dockerfile)

And lastly  -- I meant this purely as a PR at the moment simply to have a central location of discussion and so that others knew it was an idea/known enhancement.  I would really want to get some group testing/usage on it before marking it as working for the whole course work.

**Comment by colinross** [comment]
Sorry all for the late reply, I was out of town and traveling.
@pmbenjamin: I fully understand your trepidation over support issues. You are right that native docker support is beta in the full sense of the term on both windows [hyper-v based] and mac [ https://github.com/mist64/xhyve ] as they transition over to utilizing the native hypervisiors mentioned.

Currently, where I feel like docker support (in the context of the devsecops bootcamp repo) fits is at a user-contrib type level. It is available to those whom wish to utilize it as their own environment and skills/knowledge allow.

I think we can at least all agree that docker has enough critical mass of usage, even with it's 'beta' support that the project can support it this much (have a Dockerfile)

And lastly -- I meant this purely as a PR at the moment simply to have a central location of discussion and so that others knew it was an idea/known enhancement. I would really want to get some group testing/usage on it before marking it as working for the whole course work.

**Comment by slietz** [comment]
Thanks @colinross,  I think we are in agreement that docker is useful.  It would really helpful to continue to dev and provide user-contrib so that we can make it possible to complete the course using docker.

**Pull request merged**
